Add integration test
adshares/adselect pull request #75
Opened 2022-04-25 15:23 UTC by PawelPodkalicki

2022-05-06 14:14 UTC, m-pilarczyk requested changes

2022-05-06 14:14 UTC, m-pilarczyk commented on tests/Integration/IntegrationTestCase.php
> +        if ($this->esClient === null) {
```suggestion
        if (null === $this->esClient) {
```

2022-05-09 15:15 UTC, PawelPodkalicki commented on tests/Integration/IntegrationTestCase.php
> +        if ($this->esClient === null) {
Changed order

2022-05-16 07:05 UTC, m-pilarczyk approved these changes

2022-05-16 13:17 UTC, merged